### ISSUE TITLE
Language service/project system seems to break after editing for a while.

### ISSUE THREAD

**Issue by Pilchie** [dotnet/project-system#3117]
_From @CyrusNajmabadi on January 8, 2018 17:26_

I wish i had more detail to provide to help figure out what's going on here.  I've seen this happen about 5 times over the last two days of using VS 15.6.0 preview 1.  Basically i have this flow:

Make edit in some file.
Build.
Attach vs to xunit test runner
Run tests, hit breakpoints, fix issues
Rince repeat.

After some number of times doing this VS completely breaks, seemingly with a project system issue.  I say project system because one thing i've noticed is that all my usings no longer bind, and i get errors about using things like "default" (i.e. that default isn't allowed in C# 7.0, even though the project should be on a version later than that).  I have no idea what triggers this, and i can't find anything in my event log.

My only recourse is to restart VS when this happens.  Fortunately, this is much faster than it used to be so it isn't too bad.  But it's certainly a nuisance that i would love to get stamped out.

I have no idea if there's any telemetry on your side that could indicate what's going on wrong.

@sharwell @davkean @Pilchie Have you seen or heard about anything like this? 

_Copied from original issue: dotnet/roslyn#24101_

**Comment by Pilchie** [comment]
@CyrusNajmabadi if you run VS with `PROJECTSYSTEM_PROJECTOUTPUTPANEENABLED=1`, there should be an output window pane for the project system that logs what it is doing and sending to the workspace, etc.

Can you try running with that and seeing if it helps identify anything?

**Comment by Pilchie** [comment]
_From @CyrusNajmabadi on January 8, 2018 17:53_

Got this error:

![image](https://user-images.githubusercontent.com/4564579/34684343-aaff3c3c-f459-11e7-8169-c3a4afe82997.png)

Error was:

```
=====================
1/8/2018 9:51:56 AM
LimitedFunctionality
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Could not resolve mscorlib for target framework '.NETStandard,Version=v1.3'.  This can happen if the target framework is not installed or if the framework moniker is incorrectly formatted.
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUniverse..ctor(IDesignTimeAssemblyLoader assemblyLoader, IVsDesignTimeAssemblyResolution projectAssemblyResolution, IVsSmartOpenScope dispenser)
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUniverse.GetUniverse(IDesignTimeAssemblyLoader assemblyLoader, IVsDesignTimeAssemblyResolution projectAssemblyResolution, IVsSmartOpenScope dispenser)
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkProvider..ctor(IVsDesignTimeAssemblyResolution assemblyResolution, IDesignTimeAssemblyLoader assemblyLoader, TypeDescriptionProvider parentProvider, IVsSmartOpenScope openScope)
   at Microsoft.VisualStudio.ProjectUtilities.GetTargetFrameworkProvider(IServiceProvider provider, IDesignTimeAssemblyLoader assemblyLoader, IVsHierarchy hierarchy, Object instance)
   at Microsoft.VisualStudio.Design.VSTypeResolutionService.get_TypeProvider()
   at Microsoft.VisualStudio.Design.VSTypeResolutionService.ClearReferenceEntries(Boolean normal, Boolean project, Boolean disposing)
   at Microsoft.VisualStudio.Design.VSTypeResolutionService.VSLangProj._dispReferencesEvents.ReferenceRemoved(Reference r)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAVSReferences.OnReferenceRemoved(Reference reference)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ReferencesHostBridge.ApplyAsync(ReferencesDelta value)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectHostBridge`3.<>c__DisplayClass36_1.<<InitializeCoreAsync>b__3>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask`1.<JoinAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectHostBridge`3.<>c__DisplayClass36_0.<<InitializeCoreAsync>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: Could not resolve mscorlib for target framework '.NETStandard,Version=v1.3'.  This can happen if the target framework is not installed or if the framework moniker is incorrectly formatted.
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUniverse..ctor(IDesignTimeAssemblyLoader assemblyLoader, IVsDesignTimeAssemblyResolution projectAssemblyResolution, IVsSmartOpenScope dispenser)
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUniverse.GetUniverse(IDesignTimeAssemblyLoader assemblyLoader, IVsDesignTimeAssemblyResolution projectAssemblyResolution, IVsSmartOpenScope dispenser)
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkProvider..ctor(IVsDesignTimeAssemblyResolution assemblyResolution, IDesignTimeAssemblyLoader assemblyLoader, TypeDescriptionProvider parentProvider, IVsSmartOpenScope openScope)
   at Microsoft.VisualStudio.ProjectUtilities.GetTargetFrameworkProvider(IServiceProvider provider, IDesignTimeAssemblyLoader assemblyLoader, IVsHierarchy hierarchy, Object instance)
   at Microsoft.VisualStudio.Design.VSTypeResolutionService.get_TypeProvider()
   at Microsoft.VisualStudio.Design.VSTypeResolutionService.ClearReferenceEntries(Boolean normal, Boolean project, Boolean disposing)
   at Microsoft.VisualStudio.Design.VSTypeResolutionService.VSLangProj._dispReferencesEvents.ReferenceRemoved(Reference r)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAVSReferences.OnReferenceRemoved(Reference reference)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ReferencesHostBridge.ApplyAsync(ReferencesDelta value)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectHostBridge`3.<>c__DisplayClass36_1.<<InitializeCoreAsync>b__3>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask`1.<JoinAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectHostBridge`3.<>c__DisplayClass36_0.<<InitializeCoreAsync>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)<---

===================
1/8/2018 9:51:59 AM
LimitedFunctionality
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Could not resolve mscorlib for target framework '.NETStandard,Version=v1.3'.  This can happen if the target framework is not installed or if the framework moniker is incorrectly formatted.
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUniverse..ctor(IDesignTimeAssemblyLoader assemblyLoader, IVsDesignTimeAssemblyResolution projectAssemblyResolution, IVsSmartOpenScope dispenser)
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUniverse.GetUniverse(IDesignTimeAssemblyLoader assemblyLoader, IVsDesignTimeAssemblyResolution projectAssemblyResolution, IVsSmartOpenScope dispenser)
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkProvider..ctor(IVsDesignTimeAssemblyResolution assemblyResolution, IDesignTimeAssemblyLoader assemblyLoader, TypeDescriptionProvider parentProvider, IVsSmartOpenScope openScope)
   at Microsoft.VisualStudio.ProjectUtilities.GetTargetFrameworkProvider(IServiceProvider provider, IDesignTimeAssemblyLoader assemblyLoader, IVsHierarchy hierarchy, Object instance)
   at Microsoft.VisualStudio.Design.VSTypeResolutionService.get_TypeProvider()
   at Microsoft.VisualStudio.Design.VSTypeResolutionService.ClearReferenceEntries(Boolean normal, Boolean project, Boolean disposing)
   at Microsoft.VisualStudio.Design.VSTypeResolutionService.VSLangProj._dispReferencesEvents.ReferenceRemoved(Reference r)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAVSReferences.OnReferenceRemoved(Reference reference)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ReferencesHostBridge.ApplyAsync(ReferencesDelta value)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectHostBridge`3.<>c__DisplayClass36_1.<<InitializeCoreAsync>b__3>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask`1.<JoinAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectHostBridge`3.<>c__DisplayClass36_0.<<InitializeCoreAsync>b__2>d.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: Could not resolve mscorlib for target framework '.NETStandard,Version=v1.3'.  This can happen if the target framework is not installed or if the framework moniker is incorrectly formatted.
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUniverse..ctor(IDesignTimeAssemblyLoader assemblyLoader, IVsDesignTimeAssemblyResolution projectAssemblyResolution, IVsSmartOpenScope dispenser)
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUniverse.GetUniverse(IDesignTimeAssemblyLoader assemblyLoader, IVsDesignTimeAssemblyResolution projectAssemblyResolution, IVsSmartOpenScope dispenser)
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkProvider..ctor(IVsDesignTimeAssemblyResolution assemblyResolution, IDesignTimeAssemblyLoader assemblyLoader, TypeDescriptionProvider parentProvider, IVsSmartOpenScope openScope)
   at Microsoft.VisualStudio.ProjectUtilities.GetTargetFrameworkProvider(IServiceProvider provider, IDesignTimeAssemblyLoader assemblyLoader, IVsHierarchy hierarchy, Object instance)
   at Microsoft.VisualStudio.Design.VSTypeResolutionService.get_TypeProvider()
   at Microsoft.VisualStudio.Design.VSTypeResolutionService.ClearReferenceEntries(Boolean normal, Boolean project, Boolean disposing)
   at Microsoft.VisualStudio.Design.VSTypeResolutionService.VSLangProj._dispReferencesEvents.ReferenceRemoved(Reference r)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAVSReferences.OnReferenceRemoved(Reference reference)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ReferencesHostBridge.ApplyAsync(ReferencesDelta value)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectHostBridge`3.<>c__DisplayClass36_1.<<InitializeCoreAsync>b__3>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask`1.<JoinAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectHostBridge`3.<>c__DisplayClass36_0.<<InitializeCoreAsync>b__2>d.MoveNext()<---

===================
```

Is that useful info @jasonmalinowski ?

**Comment by Pilchie** [comment]
_From @CyrusNajmabadi on January 8, 2018 17:54_

And now i'm in this state:

![image](https://user-images.githubusercontent.com/4564579/34684409-dbaa6d16-f459-11e7-852a-7e8664a3b867.png)

**Comment by Pilchie** [comment]
_From @CyrusNajmabadi on January 8, 2018 17:55_

Ooops.  I mean @Pilchie .  For some reason i thought it was json responding to me.

**Comment by Pilchie** [comment]
_From @jasonmalinowski on January 8, 2018 18:12_

Looks like we should move this to https://github.com/dotnet/project-system then. I admit I don't know where the moving tool is.

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Comment by Pilchie** [comment]
@jviau or @Lifengl do you know what's up with the error above?

**Comment by Pilchie** [comment]
Ping again @Lifengl and/or @jviau ?

**Comment by jviau** [comment]
CPS is firing an event for reference removed, and the one event sink is throwing. Probably have to look into `Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUniverse..ctor(IDesignTimeAssemblyLoader assemblyLoader, IVsDesignTimeAssemblyResolution projectAssemblyResolution, IVsSmartOpenScope dispenser)`. Who owns that? I think `IVsDesignTimeAssemblyResolution.GetTargetFramework` is what eventually throws.

**Comment by Pilchie** [comment]
Your team owns that code 😄

**Comment by davkean** [comment]
We own the IVsDesignTimeAssemblyResolution implementation: https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/References/DesignTimeAssemblyResolution.cs.

**Comment by Pilchie** [comment]
Ah - for project DTAR we own it.  That makes sense.

**Comment by jviau** [comment]
Oh sorry, that isn't what is throwing, it is `VsTargetFrameworkUniverse`. `GetSystemAssembly()` returns null.

**Comment by Pilchie** [comment]
That's the part that lives in VS.  It's in `vsip\Framework\Design\VsTargetFrameworkUniverse.cs`, and I *think* your team owns that part.

**Comment by jviau** [comment]
I think the issue is this event sink is throwing and it bubbles up shutting down our dataflow, which ends up taking down all references in CPS, killing the language service. CPS should probably guard against this.

**Comment by lifengl** [comment]
That sounds right.  We should not shutdown our key data flow when one event handler throws.  But the DTAR issue should be fixed as well.  I remember David fixed a problem that we cannot load system assembly once, but don’t remember any details

Sent from my phone

On Jan 10, 2018, at 3:30 PM, Jacob Viau <notifications@github.com<mailto:notifications@github.com>> wrote:


I think the issue is this event sink is throwing and it bubbles up shutting down our dataflow, which ends up taking down all references in CPS, killing the language service. CPS should probably guard against this.

**Comment by jviau** [comment]
I opened [Bug 535156](https://devdiv.visualstudio.com/DevDiv/VS%20IDE%20CPS/_queries/edit/535156/?triage=true) to track handling of sink exceptions. For the DTAR throwing, I am not sure if the end blame is in `VsTypeResolutionService` or `VsTargetFrameworkUniverse`. Reading the original issue, I am unsure if @CyrusNajmabadi had that NFE everytime intellisense broke, or just a one time thing.

**Comment by CyrusNajmabadi** [comment]
I just hit this again.  Note this is on 15.6 preview 2 (i just upgraded today):

```
---------------------------
Microsoft Visual Studio
---------------------------
The project system has encountered an error.

 

Build target stack was corrupted and contain other unfinished targets. Expect: '_GetProjectReferenceTargetFrameworkProperties', Actual: 'ResolveProjectReferences'.



A diagnostic log has been written to the following location: "C:\Users\cyrus\AppData\Local\Temp\VsProjectFault_585e0d53-afa6-4541-ab7d-55755e92c30a.failure.txt".


---------------------------
OK   
---------------------------
```

**Comment by jviau** [comment]
This is a different error from the previous one. We attempted to fix it in 15.6, but looks like we still have issues with it. Anyways, did language service break after receiving that error? Do you always see an error dialog before language services break, or is it sometimes a silent break?

**Comment by CyrusNajmabadi** [comment]
> Anyways, did language service break after receiving that error?

Yes.  The LS was broken after this.

> Do you always see an error dialog before language services break, or is it sometimes a silent break?

On 15.6 *preview 1* i would sometimes see the dialog, but it was also sometimes silent.  For 15.6 preview 2 i do not have enough data.  What i posted above is the first issue i've encountered so far.

**Comment by lifengl** [comment]
That issue may corrupt our design time build, and causes other problems.  We made a fix in this space, but apparently, didn't fix the entire problem.

**Comment by Pilchie** [comment]
I think @cdmihai is currently looking at the Build Stack issue, and I see that  Bug 550075 was fixed by @jviau, so I *think* this is okay to close now?

**Comment by Pilchie** [comment]
Closing - please let me know if you see this again though (separate from the build stack error which @cdmihai is looking at).
