### ISSUE TITLE
SubType Designer is randomly added in csproj files

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/project-system#3186]
_From @EnCey on January 18, 2018 15:31_

### Steps to reproduce

Edit a `csproj` file and save it. A `Subtype` tag with `Designer` as content is randomly added.

```xml
<ItemGroup>
    <None Include="App.config">
        <SubType>Designer</SubType>
    </None>
    <None Include="packages.config">
        <SubType>Designer</SubType>
    </None>
</ItemGroup>
```

Here is a [Microsoft Connect issue](https://connect.microsoft.com/VisualStudio/feedback/details/783081/vs-needlessly-adds-subtype-designer-to-my-xml-documents) that describes this exact problem.

Here is a nearly a [decade old StackOverflow question](https://stackoverflow.com/questions/1573241/subtypedesigner-subtype-added-then-removed-by-visual-studio-on-load-unload) that describes this problem. According to an answer there, this issue has been present since Visual Studio 2008.

_Copied from original issue: Microsoft/msbuild#2876_

**Comment by rainersigwald** [comment]
_From @KirillOsenkov on January 25, 2018 4:55_

I wonder if it's MSBuild or it should go to https://github.com/dotnet/project-system.

cc @pilchie

**Comment by rainersigwald** [comment]
_From @KirillOsenkov on January 25, 2018 4:56_

P.S. Let's fix this, this has annoyed me for years.

**Comment by rainersigwald** [comment]
The only place I can see where we'd add this is in the pre-MSBuild-to-msbuild converter code, which should never be called:

https://github.com/Microsoft/msbuild/blob/419c6d8e55c9c8181da2ce8d0ef6f951fdfe08a3/src/Deprecated/Conversion/ProjectFileConverter.cs#L576-L578

I think this is a project system bug.

**Comment by Pilchie** [comment]
Hmm - I know how this process works for `Compile` items, but not for `.config` files.

**Comment by davkean** [comment]
@encey Can you expand on the repro steps? Which project type in particular? Can you provide the project, or record the steps that you take to reproduce this?

In .NET Framework based projects, the sub type is added for anything "designable" (Forms, Pages, Components, etc). This is being tracked by https://github.com/dotnet/project-system/issues/182. You should not hit for app.config or packages.config, that looks like a bug.

In the new project system, we do not currently add sub type unless an external component asks for it. The repro steps will help me understand what you are hitting here. Just reply to the thread with more information and I'll reopen it. Thanks!

**Comment by EnCey** [comment]
Sorry @davkean for not providing more steps. I encountered the issue while I was upgrading all projects of a solution to .NET v4.6.2 (from 4.6). 
During my investigation I found the already mentioned [StackOverflow question](https://stackoverflow.com/questions/1573241/subtypedesigner-subtype-added-then-removed-by-visual-studio-on-load-unload), in which people report this problem since Visual Studio 2008 (and still present in VS 2017). I thus thought that it would be a known issue, especially considering there's also a Microsoft Connect issue for it, which is sadly unreachable now.

In the SO question there's a link to this [MSDN forum question](https://social.msdn.microsoft.com/Forums/en-US/1c014433-95e1-46ba-8a8c-5dceaabb7ad3/what-is-subtypedesignersubtype-for-in-csproj?forum=csharpide) in which people report the issue for all kinds of project files. In my case, the sub type was definitely added to `.config` files as my example shows. 

I do not have a working repro and don't remember in which project exactly the issue occurred, but isn't a decade of reports evidence enough for your Q&A team to at least look into this? Perhaps the existing reports already contain enough information for you to identify the root cause.

When I run into the problem again I will post steps here, but for now I'm afraid I can't provide more details.

**Comment by davkean** [comment]
I've pulled the connect repro steps because Connect has been retired:

```
Repro Steps: 
1. Open attached project 
2. Go to solution explorer 
3. Double click on XML file 
4. Close solution. 
5. Nothing changes. 
6. Open attached project 
7. Go to solution explorer 
8. Right-click on XML file and select "View code" 
9. Close solution 
10. You're prompted to save changes to the project file 
11. Save the changes 
12. Project file now has needless SubType Designer decoration 

Actual Results: 
If no designer functionality is available, my project file isn't modified. 

Expected Results: 
My project is modified, causing needless version control churn.
```

Looking through all of the links you posted, there's 2, possibly 3 separate issues:

1. Project system is adding SubType to designable files. This behavior is as designed - #182 is tracking revisiting that design.
2. Something is adding SubType to XML files in some cases in VC++ files (Connect/Stackoverflow question)
3. Something is adding SubType to config/XML files in some cases in legacy C# project system

I'm going to use this bug to track the last two and find an owner. I'll dig through some code to see if/when this occurs. I suspect this is XML editor component and not the project system.

**Comment by davkean** [comment]
Could you double-click those two config files and tell me what editor opens?

**Comment by davkean** [comment]
Okay, I can see where this code lives, Package.CheckItemSubType in the XML language service (internal). Looks like both 2 & 3 above are caused by the same thing. Trying to understand the logic, and why it happens.

**Comment by davkean** [comment]
@EnCey Can I ask you a favor? Can you Help -> Send Feedback -> Report a Problem and report the same information. Once you've done that point me to it and I'll make sure it gets routed to the right team. I'll add background information to the bug about what I've found, it appears the Connect bug fell off the radar. This is a issue in the XML editor - it looks intentional that its doing this but I'm not entirely sure why.

**Comment by davkean** [comment]
Internal bug number for the connect issue is 658114.

**Comment by davkean** [comment]
I've filed https://devdiv.visualstudio.com/DevDiv/_workitems/edit/572846 internally. If/when Send Feedback, I'll associate that bug with it. Community based feedback lets other people vote on the issue and is given weight over just internal filed bugs.

**Comment by EnCey** [comment]
Hi @davkean , thank you for looking into this! 
I reported the problem like you asked [here](https://developercommunity.visualstudio.com/content/problem/204355/subtype-designer-is-added-unnecessarily-to-xml-bas.html)

**Comment by davkean** [comment]
Thanks, I've routed to the correct team.

**Comment by KirillOsenkov** [comment]
:+1:

**Comment by StingyJack** [comment]
Sorry, what's the result of this? Its kind of annoying and a minor timesink to keep coming up in pending changes or code reviews.

**Comment by EnCey** [comment]
@StingyJack and others annoyed by this bug: please head over to [the Developer Community issue](https://developercommunity.visualstudio.com/content/problem/204355/subtype-designer-is-added-unnecessarily-to-xml-bas.html) and upvote it. Leave a comment / reply if you want to generate even more buzz.

As davkean mentioned above:
> Community based feedback lets other people vote on the issue **and is given weight over just internal filed bugs**.

My personal impression of the situation is that this issue now sits in some "fix when time" backlog (aka never ;), so we'll need some noise to generate interest.

**Comment by StingyJack** [comment]
Sorry again, but devcomm is a no-go for me anymore. Less than 25% of about 230 issues i opened were resolved, and after pointing out the weird or atrocious mishandling for a few issues, it was apparently easier to suspend my accounts with a suspect excuse rather than address the mishandling problems and the unresolved issues.

**Comment by davkean** [comment]
@StingyJack If there are bugs or issues that are blocking your work that you would like to see addressed, please [open a support request](https://support.microsoft.com/en-us/getsupport?oaspworkflow=start_1.0.0.0&wf=0&wfName=productselection&gprid=1117&st=1&wfxredirect=1&sd=gn&ccsid=635804557460268950&forceorigin=esmc). Github/Developer community are intended as convenient ways to report issues and bugs to Microsoft and not intended to replace existing support mechanisms.

**Comment by StingyJack** [comment]
Sorry a third time (and final I promise) for belaboring this thread. @davkean - Is there an email address I can reach account support at? One of the unresolved issues on devcomm  is that my accounts aren't linked right.

**Comment by davkean** [comment]
Just to follow up on the thread around the original issue; this bug has been addressed and will appear in the first preview of VS 2019.

**Comment by RealDotNetDave** [comment]
Can it also be fixed in VS2017?

**Comment by davkean** [comment]
@RealDotNetDave There are no intentions to back port this fix to Visual Studio 2017. Given VS 2019 RC has been released it's moved to a servicing level where only bugs blocking major scenarios are being addressed.

**Comment by smithkl42** [comment]
Given that this is fixed in VS2019, highly ironic that I just ran into this in VS2019 :-).

I upgraded to 16.0.1 today, and when I add new classes, it insists on treating them as components, i.e.:

```
    <Compile Include="Validation\Commercial\CommercialDataValidatorBase.cs">
      <SubType>Component</SubType>
    </Compile>
```

**Comment by Pilchie** [comment]
@smithkl42 The issue was fixed for xml files (hence the original report).  For `.cs` files, the language service checks the first type in the file and all of it's base types to see if any of them have the `DesignerCategoryAttribute` applied.  If one does, that category gets written to the csproj file as the `SubType`.  It sounds like that's what is happening in your case.  If you want to override that, add a `DesignerCategoryAttribute` with a value of `code`.

**Comment by Pilchie** [comment]
See http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/DesignerAttributes/AbstractDesignerAttributeService.cs,ff002caa978ececb for where this happens.

**Comment by smithkl42** [comment]
Thanks, that explains it. We have our own `ServiceBase` class, but I accidentally had my class inheriting from `System.ServiceProcess.ServiceBase`. I'm guessing that or one of its basetypes must have the `DesignerCategoryAttribute` applied.

**Comment by oaspublic** [comment]
the problem still exists with a current visual studio. regularly after a git branch change the project files are modified with extensions or deletions of subtypes. so when changing from branch a to b the subtype is inserted and then with a future identical change from branch a to b the subtype is removed again. the behavior is very disturbing and irritating, because sometimes an automatism arises and with essential changes in prj files, sometimes accidentally wanted changes are retooled!

**Comment by SoulSeekkor** [comment]
I've never had this issue until recently (maybe the last 6 months) and it's happening in VS 2022.  Super super frustrating as I'll save my solution and it'll randomly add this subtype garbage to a VB.Net project file that I didn't even touch at all or have open.

**Comment by yuriiproniuk** [comment]
I landed on this thread with label 'Closed' happily expecting to find the solution just to find out that issue is still unresolved.
Why closing issues that are not resolved?

**Comment by SoulSeekkor** [comment]
That is a great question, unfortunately that happens with many of the VIsual Studio issues that have been around for years now.... Both on here and the Visual Studio support forums.

**Comment by julealgon** [comment]
@davkean can't you leave this open until the underlying problem is fixed? You are just creating confusion in the community with your current process.

**Comment by KirillOsenkov** [comment]
@drewnoakes

**Comment by drewnoakes** [comment]
To anyone who is still hitting this, please [file a new ticket on developer community](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022), providing repro steps (and ideally a recording of the bug happening if possible).

The bug is not related to the code in this repository, so we can't track it here. If you share a link to the ticket here, I'll make sure it's routed to the correct team. Thanks.

**Comment by rainersigwald** [comment]
No need for a new ticket unless your symptoms are very different from https://developercommunity.visualstudio.com/t/Visual-Studio-keeps-modifying-project-fi/10694196; please upvote or provide more context there.

**Comment by drewnoakes** [comment]
I suggested a new ticket because that one does not have enough information to be actionable, and adding a recording to a new ticket is easiest. If someone has clear repro steps, then maybe a comment on that PR would be adequate, but a recording of the issue happening would be helpful in the case that the repro steps don't work for whoever ends up looking at the issue.
