### ISSUE TITLE
Improve "new vs. legacy" project system detection

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4314]
Both the new and legacy project system's have a file extension of csproj/vbproj. This means that when a project opened, we need to "sniff" as to whether it needs to open in the new or legacy project system. The existing detection is called out in https://github.com/dotnet/project-system/blob/master/docs/opening-with-new-project-system.md.

This has a pretty major flaw:

- If you move the `<TargetFramework>` or `<TargetFrameworks>` elements into an import, we don't recognize it as an SDK-project and it opens in legacy, which leads to a prompt similar to below.

![image](https://user-images.githubusercontent.com/1103906/48928094-c3116a80-ef2f-11e8-8349-758106347369.png)

This prompt occurs because the project file is missing "ToolsVersion" (now optional) which makes the legacy project system think that the project comes from VS 2008 or earlier.

We should improve the detection. The detection must be extremely quick. This will run for every csproj/vbproj. This rules out doing an evaluation to figure out if the project has a `<TargetFramework>` property somewhere else in its graph, evaluations take anywhere from 10ms to 100ms and currently (due to architecture) it's extremely difficult to share this evaluation with the project system that ends up opening the project.

I propose, that we change the detection as follows.

In addition to the `</TargetFramework>` and `</TargetFrameworks>` detection[1], opt any project that is marked with an SDK, either at the project node, via the `<Sdk />` or `<Import Sdk=""/>` constructs.

This means that following 5 projects will be opt'd into the new project system:

``` XML
<Project Sdk="Microsoft.Net.Sdk">
...
</Project>
```

``` XML
<Project Sdk="Microsoft.Net.Sdk.Web">
...
</Project>
```

``` XML
<Project Sdk="MSBuild.Sdk.Extras">
...
</Project>
```

``` XML
<Project>
    <Sdk Name="My.Custom.Sdk" Version="1.0.0" />
...
</Project>
```

``` XML
<Project>
    <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
...
</Project>
```

[1] This makes sure that those that imported the SDK in an import, but left `<TargetFramework>` or `<TargetFrameworks>` element to make sure it opened in CPS still continue to open in CPS.

**Comment by drewnoakes** [comment]
If a project uses imports for the SDK and also for target framework(s), then the above sniff tests would fail. In such cases we should have a more verbose and explicit option.

For example:

```xml
<Project Sdk="Microsoft.NET.Sdk" UseManagedProjectSystem="True">
...
</Project>
```

MSBuild seems to ignore this attribute.

**Comment by davkean** [comment]
> If a project uses imports for the SDK

Do you mean has custom imports that themselves import the SDK?

**Comment by drewnoakes** [comment]
I'm thinking of the case where the SDK attribute is 'inlined', based on my understanding that the attribute essentially expands into a set of imports.

I also updated my example to not include the SDK attribute. That was misleading.

**Comment by davidhunter22** [comment]
Hi, just as a data point. I was porting an existing solution to the new project system and I ran into a problems caused by this. See https://github.com/dotnet/project-system/issues/4829#issuecomment-498070159. Fortunately davidwengier pointed me here so I can understand things a bit more. I am commenting because I do `<Import>` a file that then does a `<Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />` so the detection idiom suggested at the start of this issue would not work. I just wanted to explain why I do this for what I think is a reasonable reason.

Basically I want all output libraries, executable, ... to go to the same location. I believe this is a common feature request. To do this I set `<OutputPath>` in a file which is then imported by all the csproj files. My understanding, based on reading various things and experiment is that this must be done before the Sdk.props stuff. So in the file I import in every project I set `<OutputPath>` then do the `<Import>` of the Sdk.props. Now I could import the common file and then import the Sdk.props in every cspoj file but the common imported file contains other stuff after the import of Sdk.props which must appear after the import of Sdk.props. So I would then have to, in each csporj file, import the "pre" Sdk.props common stuff then import the Sdk.props then import the "post" Sdk.props stuff. This is of course doable but why have three lines in hundreds of csproj files when you can have one!

So even if there is a better detection mechanism I would love to have the explicit `<Project UseManagedProjectSystem="True">` suggested by drewnoakes as well.

**Comment by davkean** [comment]
> So even if there is a better detection mechanism I would love to have the explicit <Project UseManagedProjectSystem="True"> suggested by drewnoakes as well.

There is, change the GUID in the solution as called out here: https://github.com/dotnet/project-system/blob/master/docs/opening-with-new-project-system.md#project-type-guids.

**Comment by davidhunter22** [comment]
I did change the project GUID in the end now I understand what is happening. My only comment on this is that it is not at all obvious. I have spent quite a lot of time getting to this point and I'm sure others will when they try to upgrade. One other issue is that Visual Studio still uses the old FAE04EC0-301F-11D3-BF4B-00C04F79EFBC when it creates .NET Core projects. Maybe if this was fixed it would cause fewer non experts like myself to fall into this problem.

**Comment by drewnoakes** [comment]
> One other issue is that Visual Studio still uses the old FAE04EC0-301F-11D3-BF4B-00C04F79EFBC when it creates .NET Core projects.

The complexity in addressing this is that templates don't specify the project type GUID. That comes from VS based on the file extension `csproj`. Changing this is non-trivial, and looking forward the plan is to load all projects using the new project system. Investments to change how this works would become redundant in future.

**Comment by davkean** [comment]
@tmeschter Can you look into this for 16.4?

**Comment by tmeschter** [comment]
@davkean To be clear, you mean detecting an `Sdk` attribute or element and using that to opt into the CPS-based project system? Sure.

**Comment by tmeschter** [comment]
Fixed by https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/194553.

**Comment by davidwengier** [comment]
For reference of non-Microsofties the new logic implemented in that PR checks for:

* A `Project` element with an `Sdk` attribute.
* An `Import` element with an `Sdk` attribute.
* An `Sdk` element.
* A `TargetFramework` element.
* A `TargetFrameworks` element.

**Comment by drewnoakes** [comment]
There are a few extra conditions on each of those checks. To be considered an SDK-style project, it must have at least one of:

* A top-level `Project` element with an `Sdk` attribute.
* An `Import` element with an `Sdk` attribute whose parent is either a `Project` or `ImportGroup` element.
* An `Sdk` element whose parent is a `Project` element.
* A `TargetFramework` element whose parent is a `PropertyGroup` element.
* A `TargetFrameworks` element whose parent is a `PropertyGroup` element.

**Comment by Rabadash8820** [comment]
@davidwengier @drewnoakes Thanks for the clarification. I just ran into this "One-way upgrade" issue today and was tearing my hair out for a couple hours in confusion 😛. However, I'm concerned that I'm still seeing this issue in VS 16.3.9 (i.e., not being able to have a shared `TargetFramework` in `Directory.Build.props`). Has the fix that @tmeschter mentioned not been shipped yet?

**Comment by drewnoakes** [comment]
@Rabadash8820 the fix is in 16.4. You can verify this by installing one of the preview builds, or wait for the GA release.

**Comment by DanVicarel** [comment]
Excellent, thanks for the quick reply. I can wait for GA with the [`TargetFramework` workaround](https://github.com/dotnet/project-system/issues/1358#issuecomment-485243019). Keep up the good work y'all!

**Comment by Rabadash8820** [comment]
@drewnoakes I just installed VS 16.4 and can confirm that importing `TargetFramework` from a `Directory.Build.props` file is working as advertised. Thanks again!

**Comment by davkean** [comment]
@Rabadash8820 thanks for following up!
