### ISSUE TITLE
C# file in multiple csproj files in same solution can't be switched between said csprojs in vs editor

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4467]
_From @FransBouma on August 4, 2017 8:28_

Repro: [CSharpEditorRepro.zip](https://github.com/dotnet/project-system/files/1199694/CSharpEditorRepro.zip)

The attached repro case has two csproj files, one targeting NetFX and one targeting NetStandard2.0. The Netstandard2.0 project references the cs file from the NetFX project. While I know in theory one could use 'multi-targeting', for now I'm not using that due to tooling being in preview state and this allows me to build two artifacts without problems.

The issue is that when I open the C# file in the vs 2017 15.3 prev 7 editor, it will always pick the netstandard project in the top bar: you can't select the NetFX project version, even if you open that solution item. This is particularly problematic when there are conditional compilation directives present, like the one in the example. 

If there's more info needed, let me know. :)

_Copied from original issue: dotnet/project-system#2691_

**Comment by jasonmalinowski** [comment]
Moving this now back to the project system. The one remaining bug I see here is if you mix Shared Asset Projects with multitargeting projects. Imagine you have three projects:

1. A shared asset project.
2. A regular csproj project consuming this shared asset project.
3. A mutlitargeting CPS project consuming the shared asset project.

The shared asset project's IVsHierarchy has a property (VSHPROPID_SharedItemContextHierarchy) that Roslyn queries to know which context the files in the shared asset project should be in. When we are changing contexts from the regular csproj to the CPS project, we _set_ this property on the shared asset project to which project we're switching to. (Note we also set the property on the multitargeting project to specify which target is being used. For the purposes of discussion, we can ignore this.)

This ultimately results in this code being ran inside of the shared project support in CPS:

```
>	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.SharedProjectFilesPackage.SharedProjectFileNode.IsProjectAValidActiveContext(System.Tuple<Microsoft.VisualStudio.Shell.Interop.IVsHierarchy, System.Guid> sharedFileUserProject, bool reportIfNotValid) Line 1429	C#
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.SharedProjectFilesPackage.SharedProjectFileNode.EnsureActiveContextIsValid(System.Tuple<Microsoft.VisualStudio.Shell.Interop.IVsHierarchy, System.Guid> newContextToChangeTo, bool reportIfNotValid, bool deferEventFiring) Line 1356	C#
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.SharedProjectFilesPackage.SharedProjectFileManagerHierarchy.Microsoft.Internal.VisualStudio.Shell.Interop.IVsSharedMSBuildFilesManagerHierarchy.SetActiveContextForSharedMSBuildFile.AnonymousMethod__0() Line 774	C#
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.JoinableTaskFactory.ExecuteJob<Microsoft.VisualStudio.Threading.EmptyStruct>(System.Func<System.Threading.Tasks.Task> asyncMethod, Microsoft.VisualStudio.Threading.JoinableTask job)	Unknown
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.JoinableTaskFactory.RunAsync(System.Func<System.Threading.Tasks.Task> asyncMethod, bool synchronouslyBlocking, Microsoft.VisualStudio.Threading.JoinableTaskCreationOptions creationOptions, System.Delegate entrypointOverride)	Unknown
 	Microsoft.VisualStudio.ProjectSystem.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.ExecuteSynchronously(System.Func<System.Threading.Tasks.Task> asyncAction) Line 134	C#
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.SharedProjectFilesPackage.SharedProjectFileManagerHierarchy.Microsoft.Internal.VisualStudio.Shell.Interop.IVsSharedMSBuildFilesManagerHierarchy.SetActiveContextForSharedMSBuildFile(string sharedFileFullPath, Microsoft.VisualStudio.Shell.Interop.IVsHierarchy activeContextHierarchy) Line 776	C#
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ImportingProjectsService.SetSharedItemContextHierarchyAsync(Microsoft.VisualStudio.Shell.Interop.IVsHierarchy hierarchy) Line 207	C#
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.SetProperty.AnonymousMethod__0() Line 1891	C#
```

In the CPS-consuming-shared-asset-projects case, the call to set the hierarchy property is "succeeding", but internally fails. This check inside of IsProjectAValidContext is failing:

```
            else if (!this.RegisteredSharingProjectsByID.Keys.Contains(sharedFileUserProject.Item2))
            {
                // The projectID is not registered as a user of our shared MSBuild project file.
                Report.If(
                    reportIfNotValid,
                    string.Format(CultureInfo.CurrentCulture, "ActiveContext project '{0:B}' is not a registered user of shared MSBuild project file '{1}'.", sharedFileUserProject.Item2, this.FullPath));

                return false;
            }
```

So it seems CPS isn't telling the shared asset project it's actually consuming from it. This is odd, because asking the CPS project which project is hosting the items *does* return the shared asset project. So the link is happening in one way, but not the other!

I also filed [this bug](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/765434) internally where it seems once you close these solutions, there's a bunch of object disposed exceptions happening around shared asset projects. Something tells me this isn't being wired up right at all.

**Comment by davidwengier** [comment]
@jasonmalinowski I think this is a separate issue as I can reproduce these issues without multi-targetting and without regular csproj projects in the mix. Simply having two CPS projects both using a shared project means switching contexts doesn't work and results in the same "project X is not a registered user of shared MSBuild project file".

I will log a new issue for this, just need to work out if it goes here or CPS.

**Comment by davidwengier** [comment]
Logged https://devdiv.visualstudio.com/DevDiv/_workitems/edit/792775 for the remaining work.

**Comment by FransBouma** [comment]
@davidwengier That url isn't accessible. Why not log it here, as the system is OSS?

**Comment by davidwengier** [comment]
@FransBouma Unfortunately the repository where this fix needs to happen is not OSS, hence the internal work item.

Fortunately the original issue you reported (#2691) has been fixed in Roslyn with https://github.com/dotnet/roslyn/pull/32313 so should be available in the latest Visual Studio 2019 Preview. The new work item is for a separate issue to do with Shared Projects.

**Comment by FransBouma** [comment]
@davidwengier Ah, thanks for clearing that up! 😄

**Comment by weitzhandler** [comment]
Facing this nasty issue on VS 16.3.

**Comment by weitzhandler** [comment]
One of the most annoying issues I have in VS. Still occurring in 16.4.2.

**Comment by davkean** [comment]
We fixed out the root cause for the remaining issues and this will be fixed in 16.5 Preview 3: https://github.com/dotnet/project-system/pull/5805.
