### ISSUE TITLE
DependentUpon is needed for build for embedded resources

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4807]
When porting existing WPF or WinForms applications to target .NET Core that contain EmbeddedResources, the logical name is not fully defined and results in missing resources.

**Comment by davkean** [comment]
We also ran into this: https://github.com/dotnet/project-system/pull/4803

**Comment by davidwengier** [comment]
Repro: 

* Create a new SDK Windows Forms project
* Change to net472 so the designer works
* Open the designer, set "Localizable" to true in the property page
* Create a new folder
* Drag the form into the folder
* F5

**Comment by davkean** [comment]
I think we should fix this via MSBuild sniff'ing for the designer file despite the lack of DependentUpon. We need a proposal first, and at which we'll move to SDK.

**Comment by davidwengier** [comment]
This is related to AB#825236

**Comment by nguerrera** [comment]
Reluctantly agree, seeing no other option at this point. I think this can be closed against https://github.com/microsoft/msbuild/issues/4488

**Comment by ds1709** [comment]
Is there any progress with this? I'm using .Net Core 3 (WindowsDesktop/WindowsForms), and problem still exists. By the way, that was unpleasant surprise for me after migrating from classic csproj to Sdk style.

**Comment by nguerrera** [comment]
@ds1709 Please open a new issue with the details of what you are seeing. https://github.com/microsoft/msbuild/issues/4488 was implemented and should have solved the problem this tracked.
