### ISSUE TITLE
Where is `IDebugProfileLaunchTargetsProvider2` defined? 

### ISSUE THREAD

**Issue by aodl** [dotnet/project-system#5509]
I need to provide an implementation of `IDebugProfileLaunchTargetsProvider2`. I see it is defined [here](https://github.com/dotnet/project-system/blob/138f25249f2170a9cf3c3df1b6cea419f4dc469b/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/IDebugProfileLaunchTargetsProvider2.cs), but what nuget package do I need to reference in order to get at it? 

It's certainly not in the latest (even pre-release) version of the packages I'd expect. Please see [my comment on the original PR](https://github.com/dotnet/project-system/pull/3026#issuecomment-531951305)

**Comment by davidwengier** [comment]
Our packages are currently pushed to a myget feed, and not the Nuget public feed. You can find Microsoft.VisualStudio.ProjectSystem.Managed.VS here: https://dotnet.myget.org/feed/roslyn/package/nuget/Microsoft.VisualStudio.ProjectSystem.Managed.VS

**Comment by aodl** [comment]
Thanks @davidwengier, however I have the following issue when running this `nuget.exe install Microsoft.VisualStudio.ProjectSystem.Managed.VS -Version 16.4.0-beta1-64520-04 -Source https://dotnet.myget.org/F/roslyn/api/v3/index.json`

```
Unable to find a version of 'Microsoft.Build' that is compatible with 'Microsoft.VisualStudio.ProjectSystem.Managed 16.4.0-beta1-64520-04 constraint: Microsoft.Build (>= 16.1.76)', 'Microsoft.VisualStudio.ProjectSystem.Managed.VS 16.4.0-beta1-64520-04 constraint: Microsoft.Build (>= 16.1.76)'.
```

Setting up the package source in VS NuGet Package Manager and attempting to install the package, there are more missing dependencies

```
NU1101: Unable to find package Microsoft.Build. No packages exist with this id in source(s): C#, F# and Visual Basic project system
NU1101: Unable to find package Microsoft.VisualStudio.Diagnostics.PerformanceProvider. No packages exist with this id in source(s): C#, F# and Visual Basic project system
NU1101: Unable to find package Microsoft.VisualStudio.VSHelp. No packages exist with this id in source(s): C#, F# and Visual Basic project system
NU1101: Unable to find package Microsoft.Build.Engine. No packages exist with this id in source(s): C#, F# and Visual Basic project system
NU1101: Unable to find package Microsoft.VSDesigner. No packages exist with this id in source(s): C#, F# and Visual Basic project system
NU1101: Unable to find package Microsoft.VisualStudio.WCFReference.Interop. No packages exist with this id in source(s): C#, F# and Visual Basic project system
NU1101: Unable to find package Microsoft.VisualStudio.GraphModel. No packages exist with this id in source(s): C#, F# and Visual Basic project system
NU1101: Unable to find package Microsoft.Build.Utilities.Core. No packages exist with this id in source(s): C#, F# and Visual Basic project system
NU1101: Unable to find package RoslynTools.SignTool. No packages exist with this id in source(s): C#, F# and Visual Basic project system
NU1101: Unable to find package Microsoft.VisualStudio.ProjectSystem.Analyzers. No packages exist with this id in source(s): C#, F# and Visual Basic project system
NU1101: Unable to find package Microsoft.VisualStudio.ProjectSystem.SDK. No packages exist with this id in source(s): C#, F# and Visual Basic project system
NU1101: Unable to find package Microsoft.VisualStudio.XmlEditor. No packages exist with this id in source(s): C#, F# and Visual Basic project system
NU1101: Unable to find package Microsoft.VisualStudio.DataTools.Interop. No packages exist with this id in source(s): C#, F# and Visual Basic project system
NU1101: Unable to find package Microsoft.Build.Tasks.Core. No packages exist with this id in source(s): C#, F# and Visual Basic project system
NU1101: Unable to find package XliffTasks. No packages exist with this id in source(s): C#, F# and Visual Basic project system
```

The most recent version of Microsoft.VisualStudio.ProjectSystem.Managed.VS that I'm able to install without experiencing these issues is `2.5.0-beta1-6202401`. Unfortunately this doesn't contain a definition for `IDebugProfileLaunchTargetsProvider2`.

Do I need to register another package source or something?

**Comment by aodl** [comment]
@davidwengier sorry to hound you. As mentioned I resolved the issue above, but I'm still a little confused.

In my VSIX extension I can export an implementation of `IDebugProfileLaunchTargetsProvider` without problems as long as I am referencing version `2.3.6152103` (latest stable) of Microsoft.VisualStudio.ProjectSystem.Managed.VS. The problem is that I need to implement `IDebugProfileLaunchTargetsProvider2` (to satisfy [this condition](https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectDebuggerProvider.cs#L130)), however this interface hadn't yet been introduced in version `2.3.6152103` (I guess VS 2019 must be using a beta version of Microsoft.VisualStudio.ProjectSystem.Managed.VS?).

The most recent version of Microsoft.VisualStudio.ProjectSystem.Managed.VS that I am able to reference (while still being able to resolve all of the dependent packages from various myget feeds) is `16.3.0-beta1-64414-05`. This version contains a definition of `IDebugProfileLaunchTargetsProvider2` which is great, but ignoring `IDebugProfileLaunchTargetsProvider2` for the moment, it appears that I now have type identify issues messing up MEF composition. 

Without making any changes to my code and just changing the package version, my export for `IDebugProfileLaunchTargetsProvider` stops working and results in the following runtime error:
```
Microsoft.VisualStudio.ProjectSystem.VS.Debug.ProjectDebuggerProvider.ProfileLaunchTargetsProviders: is not assignable from exported MEF value CustomDebugProfileLaunchTargetsProvider.
   part definition Microsoft.VisualStudio.ProjectSystem.VS.Debug.ProjectDebuggerProvider
```

I believe this is because  `IDebugProfileLaunchTargetsProvider` has a different type identity to the `IDebugProfileLaunchTargetsProvider` expected by [ProjectDebuggerProvider](https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectDebuggerProvider.cs#L57), due to the assembly version. Can you think of what I'm doing wrong, or is there a particular version of Microsoft.VisualStudio.ProjectSystem.Managed.VS that I need to reference to both get access to `IDebugProfileLaunchTargetsProvider2` as well as satisfying what VS expects?

**Comment by aodl** [comment]
^ As an update to the above, I checked and my VS 2019 instance uses version `3.2.0-beta1-64225-04` of Microsoft.VisualStudio.ProjectSystem.Managed.VS. I've downgraded the version my VSIX extension is using to match this, and the problem is resolved for now. I can currently export my `IDebugProfileLaunchTargetsProvider2` implementation under the `IDebugProfileLaunchTargetsProvider` MEF contract. Great! :D very happy

However presumably this will be a recurring issue with subsequent VS updates until the launch profiles API has been stabilised? Is there a roadmap or rough timeframe for when this will happen? Also I'm not entirely sure why this MEF contract / type identity is currently an issue - shouldn't `IDebugProfileLaunchTargetsProvider` be defined in a separate contract assembly that doesn't need to change or have the version incremented?

**Comment by davidwengier** [comment]
I'm glad you were able to get this sorted, but unfortunately we don't have a roadmap or plan for changing our assembly layout to separate interfaces and implementation. This certainly could be a problem in future, and indeed for Visual Studio 2019 there was a breaking change made by one of our downstream dependencies that meant required different VSIXes be created for VS2017 and VS2019.

**Comment by aodl** [comment]
Ah I see, thanks for the reply. But if its a VS 2019 breaking change shouldn't it be listed [here](https://github.com/microsoft/VSProjectSystem/blob/master/doc/overview/breaking_changes_visual_studio_2019.md)? I'm asking mostly so that I know what to expect with future releases and the level of detail that breaking changes documentation will go into.

Is this a problem for all of the interfaces contained in the `Microsoft.VisualStudio.ProjectSystem` namespace? I'm asking just in case there are other interfaces that are safer to use, like `IDebugLaunchProvider` (ExportDebuggerAttribute). I know that the usage of this interface is different, but I think I could still get what I need done by exporting this instead of `IDebugProfileLaunchTargetsProvider`, and would prefer to do that if it's better insulated from breaking changes.

**Comment by adminnz** [comment]
@aodl Would you be able to share how you got your targets provider working? Because if I implement IDebugProfileLaunchTargetsProvider or IDebugProfileLaunchTargetsProvider2 and put a break point on every method. I still cannot get it to apparently get noticed by VS2019.

**Comment by MagicAndre1981** [comment]
> Our packages are currently pushed to a myget feed, and not the Nuget public feed. You can find Microsoft.VisualStudio.ProjectSystem.Managed.VS here: https://dotnet.myget.org/feed/roslyn/package/nuget/Microsoft.VisualStudio.ProjectSystem.Managed.VS

the link is broken. Where can I find the last version @davidwengier ?

**Comment by davidwengier** [comment]
@MiYanni what feed to project system packages end up in these days?

**Comment by MagicAndre1981** [comment]
> @MiYanni what feed to project system packages end up in these days?

ok, I found a pre-release feed in [this nuget.config](https://github.com/microsoft/vstest/blob/main/NuGet.config)

`https://pkgs.dev.azure.com/azure-public/vside/_packaging/vs-impl/nuget/v3/index.json`

Here I see a beta1 of the package for 16.10

**Comment by MagicAndre1981** [comment]
I also need to add the feed of XliffTasks:

`https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json`

and install several `Microsoft.CodeAnalysis` packages on my own.

**Comment by MiYanni** [comment]
@davidwengier This says: https://github.com/dotnet/project-system/blob/325b161134a9fa3fac63bacf0900030919bc54c3/build/ci/official.yml#L149

**Comment by MagicAndre1981** [comment]
> https://github.com/dotnet/project-system/blob/325b161134a9fa3fac63bacf0900030919bc54c3/build/ci/official.yml#L149
> 
> Seems to be correct. I see updated packages in that feed.

yes, I use the feed now. It would be better to have a newer stable version on nuget.org
